---
- name: Apply RDMA MachineConfig 99-{{ node_role }}-ib-core-netns
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    host: "{{ ocp_api_url }}"
    state: present
    definition: "{{ lookup('template', 'rdma_machineconfig.yml') }}"
