---
- name: Apply the Password Hasher Role
  hosts: localhost
  gather_facts: false
  vars: 
    my_predefined_core_pass: "password"

  vars_files:
    - "vars/ocp_connect.yml"
    - "vars/core_passw.yml"

  roles:
    - role: ocp_scp_role 
