apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "{{ node_role }}"
  name: "99-{{ node_role }}-lldpad"
spec:
  config:
    ignition:
      version: 3.5.0
    systemd:
      units:
        - name: lldpad.service
          enabled: true
