---
sriov_ns: openshift-sriov-network-operator
ipam_type: nv-ipam
pooltype: cidrpool
metaplg_type: rdma
networknamespace: default
cidrpool_nms: nvidia-network-operator
openshift_network_rails:
  - eth_rail0
  - eth_rail1
  - eth_rail2
  - eth_rail3
  - eth_rail4
  - eth_rail5
  - eth_rail6
  - eth_rail7
