---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ pv_name }}"
spec:
  capacity:
    storage: "{{ storage_size }}"
  accessModes:
    - "{{ access_mode }}"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "{{ nfs_server }}"
    path: "/home/nfs-share/{{ storage_name }}"
